### ISSUE TITLE
Repo Cleaning

### ISSUE THREAD

**Issue by abdullahyldz** [bounswe/bounswe2020group2#120]
1. Our repo has many unnecessary .jpg/.pod/.png files.

2. Our static folders contain files names as 1.jpg / 111.jpg / New Wireframe 2 copy 3.png etc. We can refactor the names with a nice naming convention we choose. 

My naming convention suggestion

* use lower case letters
* use the dash to split words
* use descriptive names (file's purpose should be understood from its name)

So, better naming can be

(mockups)
rating-and-reviews-of-product.png
payment-method.png

(project plan)
project-plan.jpg
project-plan-new-semester.jpg

**Comment by karalleyna** [comment]
Good point! So,
- [x]  I have removed 24 image files from images folder since they are either old version of deliverables or gifs that had been used for the design of sidebar, home page etc.
- [x] I have renamed 21 image files according to your naming convention suggestion. 
- [x] I have changed all wrong references due to this change in names.

**Comment by MehdiSaffar** [comment]
Squashed repeated commits, deleted stale branches, renamed a few commits, added tag to first dev commit, etc..
Notified everyone of the breaking updates in WhatsApp and Slack and of the need to just reclone the entire repo.
