### ISSUE TITLE
Initializing backend sub-repository

### ISSUE THREAD

**Issue by umutoksuz** [bounswe/bounswe2020group2#130]
Backend subrepo will be initialized using Django framework.

**Comment by MehdiSaffar** [comment]
Can you please do the following:

- Add a README.md explaining how to setup the venv, install packages, make it work. Please take a look at mine or Asli's for an idea.
- Add a .dockerfile so that people can use it during development and to be ready for production environment.
Questions:

Is that db.sqlite3 temporary? Should it be .gitignore'ed?
