### ISSUE TITLE
Research how to deploy Docker images to EC2

### ISSUE THREAD

**Issue by MehdiSaffar** [bounswe/bounswe2020group2#139]
Potentially directly through Github Actions.

**Comment by MehdiSaffar** [comment]
Meeting with @ozdenizdolu today 2pm

**Comment by MehdiSaffar** [comment]
likely solution for frontend:

1. build docker image in github actions
2. save it as tar.gz
3. configure aws credentials
4. scp the tar.gz to EC2 instance
5. wipe out ~/application in EC2 instance
6. reset docker state in EC2 instance
7. send commands to EC2 to run the docker image of frontend

**Comment by ozdenizdolu** [comment]
We had another meeting with @MehdiSaffar from 20:30 to 23:30 today and we had sorted out the solution proposal that Mehdi wrote above, except for:

- We need to properly configure nginx to serve index.html on custom urls.
- We need to detach the docker run command in the workflow from the github actions so that it does not wait for it to finish and get a timeout.
- We need to configure nginx to allow CORS
- We need to figure out how to pass environment variables (such as backend API URL) to the docker container
- We suggest that we create 2 different branches called backend-deploy and frontend-deploy and run the Github Actions workflows on there. So that whenever we make changes to frontend/backend and we want to deploy; we merge master into them respectively.

**Comment by MehdiSaffar** [comment]
Explained the idea in a call with Backend lead @umutoksuz
