### ISSUE TITLE
Product card styling

### ISSUE THREAD

**Issue by abdullahyldz** [bounswe/bounswe2020group2#167]
Currently, product card shape is not fixed and changes with different size images.
Another problem is that rating and add to cart button do not fit in a line for certain image sizes.

**Comment by MehdiSaffar** [comment]
I would also suggest making the size of the image have a min-width and min-height. This is because when the picture is still loading, the area that will be occupied by the image will shrink to zero first then expand to fit the image. This looks bad when you have multiple product cards in the search results, each one appearing at its own time.

**Comment by abdullahyldz** [comment]
I could not make the image square. 
I will inversitage more later, I am switching to other urgent issues.
We may require backend to store square images.

**Comment by abdullahyldz** [comment]
I made the bottom part more consistent, but it requires at least 280px to fit in a horizontal line. 
`<Link>` tags were covering whole cart, thus resulting the functionality of 'Add' button and 'Rate' components. I moved bottom part out of <Card> component.
